### ISSUE TITLE
Serve icons given a version

### ISSUE THREAD

**Issue by mondeja** [LitoMore/simple-icons-cdn#4]
Seems that currently, if you use an icon link that is removed in a major version change, the link will break without notice. That is not desirable, so what about serving icons given a optional `simple-icons` version?

**Comment by LitoMore** [comment]
Yeah. I'm thinking about how to implement this feature.

We may need to integrate [jsDelivr](https://www.jsdelivr.com) or [unpkg](https://unpkg.com) in it.

**Comment by LitoMore** [comment]
We may also need UI or a list to let users know which icons are valid in a previous version. Otherwise, this feature is not very convenient to use.

By the way, this feature might take too much Bandwidth if most users specify a version for an icon. Like:

```
https://si-cdn.vercel.com/7.16.0simpleicons
https://si-cdn.vercel.com/7.16.0simpleicons
https://si-cdn.vercel.com/7.16.0simpleicons
https://si-cdn.vercel.com/7.16.0simpleicons

```

**Comment by mondeja** [comment]
> We may also need UI or a list to let users know which icons are valid in a previous version.

I don't understand why, trying to get an icon or works or not.

> By the way, this feature might take too much Bandwidth if most users specify the version for their icons. 

I'm not too worried about it, we can always take some of the annual profits to increase the server quota, which by the way, it would be convenient if it is hosted on a subdomain of `simpleicons.org` like `cdn.simpleicons.org`.

**Comment by LitoMore** [comment]
> We may also need UI or a list to let users know which icons are valid in a previous version.

Never mind. I just overthought this requirement.

> It would be convenient if it is hosted on a subdomain of `simpleicons.org` like `cdn.simpleicons.org`.

I have added `cdn.simpleicons.org` to the project settings. The domain needs to be set.

<img width="933" alt="CleanShot 2022-10-22 at 19 44 36@2x" src="https://user-images.githubusercontent.com/8186898/197337318-3da17190-4267-43f7-ad9f-b4302b758142.png">

<img width="932" alt="CleanShot 2022-10-22 at 19 48 24@2x" src="https://user-images.githubusercontent.com/8186898/197337336-7cae5305-95bf-4af8-aea5-e642f09fb52b.png">

**Comment by LitoMore** [comment]
I can transfer this project to http://github.com/simple-icons for team maintenance.

**Comment by mondeja** [comment]
> I can transfer this project to [http://github.com/simple-icons](https://github.com/simple-icons) for easy maintenance by the team.

Yes, that would be great. I've configured the CNAME record right now.

**Comment by LitoMore** [comment]
We need to send two GET requests to `jsDelivr` or `unpkg` to claim the icon and its color.

1. GET `https://cdn.jsdelivr.net/npm/simple-icons@7.17.0/_data/simple-icons.json` to get the color.
2. GET `https://cdn.jsdelivr.net/npm/simple-icons@7.17.0/icons/simpleicons.svg` to get the SVG content.

BTW, the main difference between users choosing `simple-icons-cdn` or `jsDelivr` is the coloring feature. Users can use `jsDelivr` instead of this if they just want an older version or stick to a specific version.

So I'm not sure it's a really needed requirement for users.

**Comment by LitoMore** [comment]
Closing in favor of the latest icons only, like shields.io.
