### ISSUE TITLE
The ESM

### ISSUE THREAD

**Issue by LitoMore** [LitoMore/simple-icons-cdn#6]
They have some PRs working on it:

- https://github.com/vercel/nft/pull/297
- https://github.com/vercel/vercel/pull/7954

So we can't use ESM right now.

They have another tool http://github.com/vercel/micro but not friendly to TypeScript and ESM either.

We can also drop TypeScript and use JavaScript only.

The above are just some of my development experiences.

**Comment by user72356** [comment]
What a mess, they've been working on this PR for serveral months and no progress.

**Comment by LitoMore** [comment]
Resolved.
