### ISSUE TITLE
⚠️ cpp & notepad++ icon not wokring throwing HTTP-404 error ⚠️

### ISSUE THREAD

**Issue by artbindu** [LitoMore/simple-icons-cdn#7]
I'm using simple-icons-cdn for icons. 
Current this two icon not wokring
1. https://cdn.simpleicons.org/c++
2. https://cdn.simpleicons.org/notepad++
Throwing HTTP-404 error

This might be happening after yesterday changes

**Comment by LitoMore** [comment]
It should be fixed now.

**Comment by artbindu** [comment]
wow! 

Thank you
