### ISSUE TITLE
Icon Colour Options

### ISSUE THREAD

**Issue by adamrusted** [LitoMore/simple-icons-cdn#8]
The default behaviour of the CDN is to currently display the brand colour version.
I propose that we amend this, so by default _no_ fill colour is used - but a user can use 'brand' in either the light/dark colour to display the brand colour.

- <img src="https://cdn.simpleicons.org/adobe" width=24 height=24 /> `https://cdn.simpleicons.org/adobe/brand`
- <img src="https://cdn.simpleicons.org/adobe/black/white" width=24 height=24 /> `https://cdn.simpleicons.org/adobe`
- <img src="https://cdn.simpleicons.org/adobe/black/red" width=24 height=24 /> `https://cdn.simpleicons.org/adobe/black/brand`

**Comment by LitoMore** [comment]
They should use the jsDelivr or unpkg instead if they want the black one.

This CDN is made for those people who want colors.

**Comment by adamrusted** [comment]
But we _could_ feasibly expand the functionality of this CDN. Assuming we're well below Vercel free tier usage?

**Comment by LitoMore** [comment]
I don't want this change. This will be a breaking change for my users. I prefer to keep the current logic.

For those Notion users, they need color by default.

**Comment by adamrusted** [comment]
How's about this then. Don't break existing functionality, but reserve `brand` as a keyword that can be used in either place, that and `inherit` so that people can explicitly call for the brand colour, or for the icon to inherit the colour given by external styles.

**Comment by LitoMore** [comment]
The `currentColor` won't work. The CSS styles cannot cross HTML documents.

Currently, any non-color inputs will be treated as brand color. For example: https://cdn.simpleicons.org/discord/nothing.

So, reserving the `brand` keyword is unnecessary.

**Comment by adamrusted** [comment]
> The currentColor won't work. CSS styles cannot cross HTML documents.

Fair enough. I'll remove 'inherit' from the PR.

> Currently, any non-color inputs will fallback to brand color.

What about in the dark mode color - for example:

`https://cdn.simpleicons.org/adobe/black/nothing`

**Comment by LitoMore** [comment]
As my documentation mentioned:

> Passing in an invalid value will use the default color as a fallback.

**Comment by adamrusted** [comment]
> As my documentation mentioned:
> 
> > Passing in an invalid value will use the default color as a fallback.

It doesn't work for the dark-mode colour.
See https://cdn.simpleicons.org/adobe/white/nothing

**Comment by LitoMore** [comment]
It should be fixed now.
